Add Case Id as a mandatory value
ONSdigital/go-launch-a-survey pull request #114
Opened 2018-08-17 13:39 UTC by jonnyshaw89

Added `case_id` as mandatory for all schemas

2018-08-17 14:02 UTC, bitdivision approved these changes

2018-08-20 07:20 UTC, dcdarrell9 requested changes
Does a default need to be added here? Or if the default gets changed anyway can we remove some of these? 
https://github.com/ONSdigital/go-launch-a-survey/blob/13c0997bb289f529f3371066df2da0da101c5ac7/authentication/auth.go#L448

2018-08-20 08:02 UTC, jonnyshaw89 commented
@dcdarrell9 I don't think we need it as we always set it for quick-launch
https://github.com/ONSdigital/go-launch-a-survey/pull/114/files#diff-338987301073a98ce4db3faf2cc35204R135
Test it and see?

2018-08-20 08:38 UTC, bitdivision commented
I've tested and it does work fine without the default.

2018-08-20 09:30 UTC, dcdarrell9 approved these changes

2018-08-20 10:16 UTC, merged