Make optional JSON metadata optional
ONSdigital/go-launch-a-survey pull request #16
Opened 2017-07-25 09:51 UTC by ajmaddaford

Omit empty claims that are optional in survey runner. Without this it is impossible to create a valid token that omits these values.

2017-07-25 10:20 UTC, jonnyshaw89 requested changes

2017-07-25 10:20 UTC, jonnyshaw89 commented on authentication/auth.go
>  type variantFlags struct {
i think `sexual_identity` should also be optional?

2017-07-25 15:29 UTC, jonnyshaw89 approved these changes

2017-07-26 09:58 UTC, dwyeradam approved these changes

2017-07-26 10:12 UTC, merged