updated README to include updated instructions
ONSdigital/go-launch-a-survey pull request #48
Opened 2018-02-12 11:27 UTC by MIslam92

### What is the context of this PR?
We were missing out on instructions on how to run go launcher while passing a JSON in the URL

Card: https://trello.com/c/rB9UIsm1/1830-add-supply-url-in-parameter-for-launcher-url-info-to-readme

### How to review
Check that the README makes sense

2018-02-12 13:33 UTC, jonnyshaw89 requested changes

2018-02-12 13:33 UTC, jonnyshaw89 commented on README.md
> +### Run
This heading should be clearer that this is about quicklaunch

2018-02-13 10:15 UTC, jonnyshaw89 approved these changes

2018-02-13 13:29 UTC, dwyeradam approved these changes

2018-02-13 13:35 UTC, merged