Changed survey names used in titles
ONSdigital/go-launch-a-survey pull request #85
Opened 2018-05-29 13:23 UTC by AndrewTorrance

Changed name so as to make surveys used in testing titles appear together on the list and have a common name format test_titles_..... json

2018-05-30 15:01 UTC, davecharles commented on surveys/surveys.go
> -		LauncherSchemaFromFilename("rsi_transformation.json"),
Is removing `test_date_validation_mm_yyyy_combined.json` and `rsi_transformation.json` intentional?

2018-05-30 16:07 UTC, davecharles requested changes
There are missing schema, need to check branch is up to date.

2018-06-01 06:25 UTC, shahi645 approved these changes

2018-06-01 08:28 UTC, davecharles approved these changes

2018-06-01 10:55 UTC, merged