Mutually Exclusive Checkbox Schema
ONSdigital/go-launch-a-survey pull request #86
Opened 2018-05-30 14:09 UTC by dwyeradam

Add test schema for mutually exclusive checkboxes.

2018-05-30 14:10 UTC, nealedj requested changes

2018-05-30 14:10 UTC, nealedj commented on surveys/surveys.go
> +		LauncherSchemaFromFilename("test_checkbox_mutually_exclusive"),
Missing `.json`?

2018-05-30 14:11 UTC, dwyeradam commented on surveys/surveys.go
> +		LauncherSchemaFromFilename("test_checkbox_mutually_exclusive"),
oops, works though.

2018-05-30 14:12 UTC, nealedj commented on surveys/surveys.go
> +		LauncherSchemaFromFilename("test_checkbox_mutually_exclusive"),
Oh yeah, the eq_id and form_type just get extracted.

2018-05-30 14:13 UTC, nealedj approved these changes

2018-05-31 10:13 UTC, shahi645 approved these changes

2018-05-31 10:13 UTC, merged