Cater for region code in quick launch URL
ONSdigital/go-launch-a-survey pull request #89
Opened 2018-06-05 16:03 UTC by davecharles

### What is the context of this PR?

We want to share a simple quick launch URL to launch schemas that have different behaviours based on region-code with business stakeholders.  For this to work it should be possible to specify a region code in the URL.  This change adds that capability.

### How to review 
Checkout and build go launcher, run a local eq-runner.  Use this URL to launch lms (which has country code dependant routing):

http://localhost:8000/quick-launch?url=https://raw.githubusercontent.com/ONSdigital/eq-survey-runner/master/data/en/lms_1.json&region=GB-WLS

Run the survey to Question `What do you consider your national identity to be?`:
- `Welsh` should be first checkbox
- After continue, you should see the `understand-welsh` question.

2018-06-06 08:24 UTC, nealedj requested changes

2018-06-06 08:24 UTC, nealedj commented on launch.go
> +	regionCode := r.URL.Query().Get("region")
Rather than calling `Query()` twice you could do:

```
	queryString := r.URL.Query()
	surveyURL, regionCode := queryString.Get("url"), queryString.Get("region")
```

2018-06-06 08:24 UTC, nealedj commented on authentication/auth.go
> +        if regionCode != "" {
Given that `accountURL` is set within the `generateDefaultClaims` function I think it'd make sense to do the same with regionCode.

At this point the method isn't really generating the default claims anymore. It's just generating claims. Perhaps you could remove `generateDefaultClaims` and `generateClaimsFromPost` in favour of a single `generateClaims` function. That could look like this:

```

func getStringOrDefault(key string, values map[string][]string, defaultValue string) string {
	var value string
	if keyValues, ok := values[key]; ok {
		value = keyValues[0]
	} else {
		value = defaultValue
	}
	return value
}

func generateClaims(claimValues map[string][]string) (claims EqClaims) {
	userID := getStringOrDefault("user_id", claimValues, "UNKNOWN")
	periodID := getStringOrDefault("period_id", claimValues, "201605")
	periodStr := getStringOrDefault("period_str", claimValues, "May 2017")
	collexSID := getStringOrDefault("collection_exercise_sid", claimValues, randomStringGen())
	ruRef := getStringOrDefault("ru_ref", claimValues, "12346789012A")
	ruName := getStringOrDefault("ru_name", claimValues, "ESSENTIAL ENTERPRISE LTD.")
	refPStartDate := getStringOrDefault("ref_p_start_date", claimValues, "2016-05-01")
	refPEndDate := getStringOrDefault("ref_p_end_date", claimValues, "2016-05-31")
	returnBy := getStringOrDefault("return_by", claimValues, "2016-06-12")
	tradAs := getStringOrDefault("trad_as", claimValues, "ESSENTIAL ENTERPRISE LTD.")
	employmentDate := getStringOrDefault("employmentDate", claimValues, "2016-06-10")
	regionCode := getStringOrDefault("region_code", claimValues, "GB-ENG")
	languageCode := getStringOrDefault("language_code", claimValues, "en")
	caseRef := getStringOrDefault("case_ref", claimValues, "1000000000000001")
	accountURL := getStringOrDefault("account_url", claimValues, "")

	var sexualIdentity bool
	if sexualIdentityValues, ok := claimValues["sexual_identity"]; ok {
		sexualIdentity = sexualIdentityValues[0] == "true"
	} else {
		sexualIdentity = true
	}

	var roles []string
	if rolesValues, ok := claimValues["roles"]; ok {
		roles = rolesValues
	} else {
		roles = []string{"dumper"}
	}

	claims = EqClaims{
		UserID:                userID,
		PeriodID:              periodID,
		PeriodStr:             periodStr,
		CollectionExerciseSid: collexSID,
		RuRef:          ruRef,
		RuName:         ruName,
		RefPStartDate:  refPStartDate,
		RefPEndDate:    refPEndDate,
		ReturnBy:       returnBy,
		TradAs:         tradAs,
		EmploymentDate: employmentDate,
		RegionCode:     regionCode,
		LanguageCode:   languageCode,
		TxID:           uuid.NewV4().String(),
		VariantFlags: variantFlags{
			SexualIdentity: sexualIdentity,
		},
		Roles:             roles,
		CaseID:            uuid.NewV4().String(),
		CaseRef:           caseRef,
		AccountServiceURL: accountURL,
	}

	return claims
}

```

Then claim values could be passed like:

```
func GenerateTokenFromDefaults(url string, regionCode string, accountURL string) (token string, error string) {
	claimValues := make(map[string][]string)
	claimValues["account_url"] = []string{accountURL}
	claimValues["region_code"] = []string{regionCode}

	claims := EqClaims{}
	claims = generateClaims(claimValues)
         ....
```

At that point we can easily add in new default values. In fact, we could simply pass the querystring values through directly and then we could override any claim in the query string: (we still need to patch `accountUrl` as it gets some logic applied to it)

```
func GenerateTokenFromDefaults(url string, accountURL string, getValues url.Values) (token string, error string) {
	claims := EqClaims{}
	getValues["account_url"] = []string{accountURL}
	claims = generateClaims(getValues)
```
and
```

func quickLauncherHandler(w http.ResponseWriter, r *http.Request) {
	hostURL := settings.Get("SURVEY_RUNNER_URL")
	accountURL := getAccountURL(r)
	queryValues := r.URL.Query()
	surveyURL := queryValues.Get("url")
	log.Println("Quick launch request received", surveyURL)

	token, err := authentication.GenerateTokenFromDefaults(surveyURL, accountURL, queryValues)
```

2018-06-06 08:27 UTC, davecharles commented on launch.go
> +	regionCode := r.URL.Query().Get("region")
Makes sense

2018-06-06 12:40 UTC, AndrewTorrance requested changes
Agree with Dave about it no longer being GenerateTokenFromDefaults

2018-06-06 15:20 UTC, nealedj approved these changes

2018-06-07 07:02 UTC, shahi645 approved these changes
All looks good to me. Tested and verified. Probably needs one more review, as i'm not too familiar with GO, but i can't see anything wrong with code. 🥇

2018-06-07 08:12 UTC, AndrewTorrance approved these changes

2018-06-07 08:31 UTC, merged